### ISSUE TITLE
Add default image

### ISSUE THREAD

**Issue by pjhampton** [pjhampton/Gramophone#102]
Currently, there is just a placehold.it image in place when there is no featured image. It would be awesome if we could replace it with an image of a vectorized gramophone. The code to change is: https://github.com/pjhampton/Gramophone/blob/5f2e9ae0ba3b48d6542d6816163ac7cae3ba7bb6/home.php#L55

![screen shot 2017-10-26 at 9 20 25 pm](https://user-images.githubusercontent.com/8960296/32075220-10bea666-ba94-11e7-93c8-31656cecff5e.png)

**Comment by brunockl** [comment]
I can work on this!
