### ISSUE TITLE
Style WordPress Widgets

### ISSUE THREAD

**Issue by pjhampton** [pjhampton/Gramophone#11]
# Style WordPress Widgets ✨  🚀

The default WordPress widgets could do with some light styling changes.
- **Search** - apply `.form-control` class to search box + bootstrap css class to button
- **Recent Posts** - with and without dates
- **Recent comments**
- **Archives** - when displayed as a dropdown, the select element needs the class `.form-control`

**Comment by fvaneldijk** [comment]
Hi @pjhampton, do you have a list of all the WordPress and WooCommerce widgets that need to be styled? Also, what kind of styling are you thinking of?

**Comment by pjhampton** [comment]
Hey @fvaneldijk!!

I thought about this again. Maybe WordPress _and_ WooCommerce widget styling is too ambitious for one PR. I have reduced the scope down to just WordPress widget styling issues. Let me know you thoughts 🍰

**Comment by fvaneldijk** [comment]
Hey @pjhampton,

Sounds good to only style the default WordPress widgets, it's quite the list already! :smile: 
And about the styling. I'm thinking of re-using the styling of Bootstrap components for the widgets. If I can't re-use it I'll try to imitate the Bootstrap look and feel for the WordPress widgets. Good idea?

Just to check if I have the correct list of widgets. Below are the default widgets I know of. Could you check if I covered them all?

1. Archives
2. Calendar
3. Categories
4. Custom Menu
5. Meta
6. Pages
7. Recent Comments
8. Recent Posts
9. RSS
10. Search
11. Tag Cloud
12. Text

**Comment by pjhampton** [comment]
That looks and sounds good @fvaneldijk! 

Yeah, my advice is add as little of CSS as possible and try just to leverage the bootstrap classes! 😄 
Do you want to take this forward?

**Comment by fvaneldijk** [comment]
Hi @pjhampton, sure thing. I'll claim this one and try to push it this week :smile:

**Comment by pjhampton** [comment]
You rock @fvaneldijk!! 🎉

**Comment by RickBakkr** [comment]
Is this issue still open @pjhampton @fvaneldijk ?

**Comment by pjhampton** [comment]
Yeah, it is @RickBakkr 😄

**Comment by LiamBailey** [comment]
I would like to take this issue if possible?

**Comment by pjhampton** [comment]
Hey @LiamBailey,

Sure thing. It's all yours!

**Comment by LiamBailey** [comment]
Awesome - thanks

**Comment by RickBakkr** [comment]
Sorry for posting this here: Got something you want me to do  @pjhampton ?

**Comment by pjhampton** [comment]
@RickBakkr here is a Low hanging fruit if you want an easy one https://github.com/pjhampton/Gramophone/issues/73 😄  just comment underneath!

**Comment by LiamBailey** [comment]
Just to be clear, - you want for me to insert the bootstrap classes into the widgets any way this can be done. Like the search widget uses get_search_form so if I hook into that function (filter) I can check if it is being called from the widget and add the bootstrap classes - I am asking in case I am totally missing something here :-)

**Comment by pjhampton** [comment]
Hey @LiamBailey - yep, sounds like you've got this 💪

**Comment by LiamBailey** [comment]
Just to let you know @pjhampton I have decided to add the bootstrap classes to not only the search form within the widget but in general, as your theme has no template for the search form and the plain one sucks

**Comment by LiamBailey** [comment]
If you disagree with this decision it is a simple matter of using debug_backtrace to only add the styles when the get_search_form is called within the widget.

**Comment by LiamBailey** [comment]
@pjhampton You can check out the search widget in the footer of http://46.101.6.230/ make sure I am on the right track

**Comment by LiamBailey** [comment]
^^ Search widget in footer :-)

**Comment by pjhampton** [comment]
Hey @LiamBailey 

This looks great! Awesome job so far 😄

**Comment by pjhampton** [comment]
Closed in https://github.com/pjhampton/Gramophone/pull/78
