### ISSUE TITLE
Design a better 404 page

### ISSUE THREAD

**Issue by pjhampton** [pjhampton/Gramophone#115]
Looking for help in designing a better 404 page. I like the look of something like this - super simple: http://themereact.herokuapp.com/3.0/404.html 

![screen shot 2018-10-07 at 23 04 29](https://user-images.githubusercontent.com/8960296/46587512-968bb700-ca85-11e8-93d8-30ada741a2cf.png)

**If you would like to work on this then please comment below to claim it so someone else doesn't work on it!**

**Comment by harry-7** [comment]
I want to work on this, can you assign this to me?

**Comment by pjhampton** [comment]
Sure - I have sent you a collaborator invite. The issue is all yours. No other PR will be accepted for this but yours so please work away 👍

**Comment by richtepa** [comment]
Hey @harry-7 - Are you working on it? If you stopped, I would like to work on this issue.

**Comment by harry-7** [comment]
I started working on it. I will be able to send a PR by tonight.

**Comment by richtepa** [comment]
No problem, take your time...

**Comment by harry-7** [comment]
@pjhampton Just to confirm, the screenshot you provided is how you are expecting the 404 page to look like?

**Comment by pjhampton** [comment]
@harry-7 that is what is looks like currently - you can see this in the 404.php file. I imagine something a little more cool and contrast with the rest of the site to let users know there is something wrong - kind of like http://themereact.herokuapp.com/3.0/404.html

@richtepa are you looking for a hacktoberfest issue? there is a couple I haven't put up yet

**Comment by harry-7** [comment]
@pjhampton , I am able to set the wordpress and this theme in it. But I am unable to access this 404 page. Like if I try to access some random url, I am just getting the default 404 page of apache. Is there something wrong I am doing?
![screenshot_2018-10-08 404 not found](https://user-images.githubusercontent.com/12495975/46632298-1b3c0b00-cb42-11e8-99b4-3b9bb0ef2b21.png)

**Comment by pjhampton** [comment]
That looks to be more of an apahce default 404, rather than a wordpress 404. 

Does this help? https://serverfault.com/questions/501147/wordpress-permalinks-reach-apache-404-not-wordpress-404-php-or-their-real-respec

**Comment by harry-7** [comment]
@pjhampton  thanks for the link. I was wondering if we could get rid of the nav bar for the 404 page, because we are already showing link to the main page in the 404 page. So I think, navbar is sort of redundant and also UI would look better without the navbar in the 404 page.

**Comment by richtepa** [comment]
> @harry-7 that is what is looks like currently - you can see this in the 404.php file. I imagine something a little more cool and contrast with the rest of the site to let users know there is something wrong - kind of like http://themereact.herokuapp.com/3.0/404.html
> 
> @richtepa are you looking for a hacktoberfest issue? there is a couple I haven't put up yet

No, have done enough. I just had the idea to use a broken vinyl record as zero in "404".
