### ISSUE TITLE
Fix errors on Gallery

### ISSUE THREAD

**Issue by pjhampton** [pjhampton/Gramophone#116]
There seems to be a lot of errors in the gallery which sucks.
It would be awesome if someone could make sure they are removed.

Please comment below to claim this issue

<img width="1280" alt="screen shot 2018-10-08 at 20 41 39" src="https://user-images.githubusercontent.com/8960296/46630054-e5475880-cb3a-11e8-806d-7748f23ae2d9.png">

**Comment by Pielgrin** [comment]
taken

**Comment by pjhampton** [comment]
Thanks @pielgrin! Reach out if you need any help :smile:

**Comment by Pielgrin** [comment]
This is weird @pjhampton I have no problem with the gallery on my post. What have you done to get these errors ? 
<img width="1418" alt="no bug" src="https://user-images.githubusercontent.com/18363758/46633022-c8b41c00-cb4c-11e8-9017-20c036b43157.png">

**Comment by pjhampton** [comment]
Hey @Pielgrin 

Have you got WP_DEBUG set to true in wp-config?

<img width="1280" alt="screen shot 2018-10-08 at 21 55 35" src="https://user-images.githubusercontent.com/8960296/46633230-f8f7bc80-cb44-11e8-8827-bed4ee1e53bc.png">

**Comment by Pielgrin** [comment]
Thank you ! Pull request uploaded ;)
