### ISSUE TITLE
Center video in middle of screen

### ISSUE THREAD

**Issue by pjhampton** [pjhampton/Gramophone#117]
This looks a bit too basic. It would be good to center this in the middle of the screen

If you want to work on this please claim it below in a comment

<img width="1280" alt="screen shot 2018-10-08 at 21 13 03" src="https://user-images.githubusercontent.com/8960296/46631355-0f027e80-cb3f-11e8-80b1-b111a7856591.png">

**Comment by arnas** [comment]
I will take it :)

**Comment by pjhampton** [comment]
Thanks @arnas! Reach out if you need any help 😄

**Comment by arnas** [comment]
Hey, I have created pr for this issue https://github.com/pjhampton/Gramophone/pull/120
