### ISSUE TITLE
Design the gallery

### ISSUE THREAD

**Issue by pjhampton** [pjhampton/Gramophone#118]
So the gallery looks pretty naff - because it has no styling.

It would be cool to get a bit of basic styling in here. Please comment below if you are going to work on this

<img width="1280" alt="screen shot 2018-10-08 at 21 35 26" src="https://user-images.githubusercontent.com/8960296/46632370-54747b00-cb42-11e8-9c8d-26336a015398.png">

**Comment by harry-7** [comment]
I want to take it @pjhampton. Can you throw some light on "basic styling"? Like what sort of styling you are expecting and all?

**Comment by pjhampton** [comment]
That would be awesome to have your help again @harry-7 
I really appreciate it. 

As for your question, just something simple. The purpose of this project is to do incremental development until it's as good as it gets.

I think a great start would be to align the images.

**Comment by pjhampton** [comment]
No, that's cool @harry-7 I understand.

The best way to get started is to import the following test data: https://codex.wordpress.org/Theme_Unit_Test

You will get a gallery for free in that.

**Comment by harry-7** [comment]
I created a PR for this. But If I may, I would request you to not close this issue. I feel there is a lot of scope for improvement here. So what I would suggest is that, add a checklist here with the possible improvements so that me or someone else later can look at it and contribute to it

**Comment by pjhampton** [comment]
Sure, @harry-7 
What have you got in mind?

**Comment by harry-7** [comment]
In the mean time, we can merge this PR and then make seperate PR in case we fumble upon other good to have features

**Comment by pjhampton** [comment]
Yeah, good idea @harry-7. If you come up with any ideas yourself, please feel free to create an issue and add a hacktoberfest label.
