### ISSUE TITLE
Add sidebar menu 

### ISSUE THREAD

**Issue by pjhampton** [pjhampton/Gramophone#123]
It would be pretty dope to have a sidebar nav. This would be done by creating a header-sidebar.php template and adding additional css to the app.css file. There is a header-nonav.php file which is used in 404.php

The kind of thing that I am thinking of is

http://themereact.herokuapp.com/3.0/index3.html

**Comment by harry-7** [comment]
I will take this. I kind of wanted to suggest this.

**Comment by pjhampton** [comment]
Thanks @harry-7!

**Comment by pjhampton** [comment]
Hey @harry-7! How are you getting on? Do you require any assistance? :)

**Comment by harry-7** [comment]
@pjhampton , Sorry, I forgot to update you. I searched online for some tutorials, I went through them and I felt they are good. I was unsure, whether I can build similar things here as well. Will there be some licence issues or something like that?

**Comment by pjhampton** [comment]
There shouldn't be as long as it's not copied verbatim :smile: 
If you feel it might be too much of a challenge I don't mind taking over?

**Comment by harry-7** [comment]
@pjhampton I will try for a day or two and then I will let you know?

**Comment by pjhampton** [comment]
Hey. Going to close this out.
