### ISSUE TITLE
Post Format Development (audio)

### ISSUE THREAD

**Issue by pjhampton** [pjhampton/Gramophone#19]
# Welcome 🚀

WordPress supports [Post Formats](https://codex.wordpress.org/Post_Formats) out of the box. As this starter theme is focused on top-down development, all Post Formats available should be provided out of the box. The various post formats include:
- aside 
- gallery
- link
- image
- ~~quote~~ - COMPLETE
- status
- video
- **audio**
- chat
## The Goal

The goal of up and coming PR will be to _alter_ and _style_ **BigBooty/formats/format-audio.php**
According to the [WordPress codex](https://codex.wordpress.org/Post_Formats):

> audio - An audio file or playlist. Could be used for Podcasting.

You can activate the format from the Post Editing window like so:

![screen shot 2016-10-04 at 10 09 13 am](https://cloud.githubusercontent.com/assets/8960296/19068456/a11be544-8a1a-11e6-8b70-827741f97c9b.png)
## How to Contribute

Just claim the issue below and start hacking. It is granted on a first come first serve basis.

**Comment by rveitch** [comment]
@pjhampton I'm happy to claim and take a crack at this one for Hacktoberfest, I've previously done work on both WordPress based Bootstrap 4 themes and audio/podcast related plugins before.

**Comment by pjhampton** [comment]
Awesome @rveitch 💙  ❤️  It's all yours!! Make it your own, but feel free to reach out if you need any help 😄

**Comment by pjhampton** [comment]
Hey @rveitch!

There is only another 24 hours of hacktoberfest left. Would you like to send a PR so you don't lose out on this?
