### ISSUE TITLE
New theme name

### ISSUE THREAD

**Issue by pjhampton** [pjhampton/Gramophone#22]
# New Theme Name 🚀

I have used this theme in production a couple of times now, and since I'm opening it up to the world it might be a good idea to give it a new name, possibly a new home in a Github organization. I'm terrible at naming things. Does anybody have any ideas?

**Comment by pjhampton** [comment]
I'm considering to rename this theme to `Gramaphone` in the new year (to start the spitting balling off). Does anybody have any opinions, etc?

**Comment by RickBakkr** [comment]
How about Wordstrap (already exists in WP catalog, but hasn't been updated for over 2 years) or Bootpress? I think it would be a nice name since it (partially) includes the names of 2 main pieces of software involved: Bootstrap and Wordpress. What do you think? Gramaphone is a nice name either ;-)

**Comment by pjhampton** [comment]
The theme has been renamed.
