### ISSUE TITLE
Style WooCommerce Widgets

### ISSUE THREAD

**Issue by pjhampton** [pjhampton/Gramophone#55]
The following WooCommerce Widgets need bootstrap boilerplate styling. These include:
- WooCommerce Average Rating Filter
- WooCommerce Layered Nav Filters
- WooCommerce Basket
- WooCommerce Price Filter
- WooCommerce Product Categories
- WooCommerce Product Tags
- WooCommerce Recently Viewed
- WooCommerce Recent Reviews
- WooCommerce Top Rated Products

Reseved for @RickBakkr

**Comment by RickBakkr** [comment]
Are these widgets meant to be put in "Page widget" or in one of the places at the footer? Nothing shows up when I use it in Page though...

**Comment by pjhampton** [comment]
Yeah, it should be in page widget. It seems there is a bug. I will look into this and get back to you.

**Comment by pjhampton** [comment]
Hey @RickBakkr 

Can you import the dummy data from here (https://docs.woocommerce.com/document/importing-woocommerce-dummy-data/) and import it. Are you still experiencing problems?

**Comment by RickBakkr** [comment]
Hi @pjhampton 

Actually, that was the first thing I did after installing Woocommerce. I am still not seeing any widget when I put it in the "Page widget" spot.

**Comment by pjhampton** [comment]
Hmm, is it set to the default template in the page settings?

**Comment by RickBakkr** [comment]
I think so. These page settings are currently set:

http://i.imgur.com/HPvRCaW.png

**Comment by pjhampton** [comment]
That is weird! Last question, if you add the likes of standard WP widgets to it, such as Search, or text - does it show up?

**Comment by RickBakkr** [comment]
Nope. Tested a search form in the Page widget, it did not show up.

**Comment by pjhampton** [comment]
Ok, I will get back to debugging.

**Comment by RickBakkr** [comment]
Did you make any progress into this matter @pjhampton ?

**Comment by pjhampton** [comment]
Hey @RickBakkr 

I'm afraid I can't replicate this at all. I am assuming it has something to do with your setup. Can you double check on your end?

**Comment by RickBakkr** [comment]
Seems like this project is no longer active? Want to see whether I have the time to dig into this issue again upcoming week :-)

**Comment by pjhampton** [comment]
Hey @RickBakkr,

The project is still being maintained, I'm just crazy buzy at the moment. Yeah, I would love some help 😄  I removed woocommerce for now because it was getting messy
