### ISSUE TITLE
Fix Product layout

### ISSUE THREAD

**Issue by pjhampton** [pjhampton/Gramophone#56]
For some reason, when there is a bit more text in the product title, it messes up the bootstrap rows / columns. This needs to be fixed. If you are interesting in working on this issue, please comment below to claim it.

![screen shot 2016-10-19 at 10 44 17 am](https://cloud.githubusercontent.com/assets/8960296/19513826/450dfc30-95e9-11e6-9de6-2e364fe11412.png)

**Comment by xRahul** [comment]
I'll work on it.. I have some experience with this issue

**Comment by pjhampton** [comment]
Awesome @xRahul 😄  Look forward to seeing your PR

**Comment by pjhampton** [comment]
How are you getting on @xRahul? 😄 
Do you have any questions?

**Comment by xRahul** [comment]
actually I'm still checking out the code.. It'll take me some time to get through it all

**Comment by pjhampton** [comment]
No problem @xRahul :) feel free to reach out if you need any help!

**Comment by xRahul** [comment]
Hey @pjhampton 
How do I reproduce this issue? I'd need to add some dummy products and maybe use some plugin, right? I have installed wordpress and activated the BigBooty Theme just fine. Now what?

**Comment by xRahul** [comment]
Also check this out- https://github.com/pjhampton/BigBooty/pull/68

**Comment by pjhampton** [comment]
As this is a starter theme, we want any css / sass / etc to be as minimal as possible. Have you seen a this? http://stackoverflow.com/a/20258406/3968703

**Comment by xRahul** [comment]
@pjhampton I know about those ways, but they are restrictive. For the clearfix way, you'd have to define a fixed number of elements per row, like say 4.
This is bad as bootstrap is responsive, and you want the layout to vary with size.. as in, for lg it's 4, md it's 3 and sm/xs it's 2 per row.
Also even if we fix the number of elements per row, the rows would look too mismatched due to different heights.

**Comment by pjhampton** [comment]
Hey @xRahul 

It sounds like you know what you are talking about so I will let you choose the right direction 😄

**Comment by pjhampton** [comment]
Hey @xRahul!

Just to let you know that there is only another 24 hours of hacktoberfest left. Do you want to at least send a PR to reserve this?
