### ISSUE TITLE
Design: Create new logo / splash for Gramophone

### ISSUE THREAD

**Issue by pjhampton** [pjhampton/Gramophone#71]
After last years Hacktoberfest, I renamed the theme to something more... mature and family friendly 😆 . As such, the project needs a new identity, ie: a logo and a splash for the README (see below images).

My kind of thinking is around the lines of: 

- https://www.shutterstock.com/image-vector/gramophone-icon-401650771?src=D9TK-ESOVVQ01kyN9Hdzaw-1-15
- https://www.shutterstock.com/image-vector/old-gramophone-isolated-icon-design-vector-440255527?src=RKatnuqnAuLvNMlZ0yctjA-1-33
- https://www.shutterstock.com/image-vector/old-gramophone-isolated-icon-design-vector-440254702?src=RKatnuqnAuLvNMlZ0yctjA-1-58

It would be able to incorporate WP in there somewhere.

![screen shot 2017-10-01 at 5 35 13 pm](https://user-images.githubusercontent.com/8960296/31056792-c115f128-a6cf-11e7-84c8-f3aceb4dc836.png)
![screen shot 2017-10-01 at 5 35 28 pm](https://user-images.githubusercontent.com/8960296/31056793-c130fa2c-a6cf-11e7-8df2-48cb7f81960a.png)

**Comment by richtepa** [comment]
*Made one.*

Something like this?
![design](https://user-images.githubusercontent.com/32306396/31057709-a2203770-a6e7-11e7-9f40-665a1dd9817f.png)

**Comment by pjhampton** [comment]
Nice, @richtepa! Thanks :-)
Do you want to submit a PR to the PR replacing `./screenshot.png`? You will get the hacktoberfest credit this way. Also, please make note of the dimensions of the currently one - these are the correct dimensions!

**Comment by richtepa** [comment]
done
#74

**Comment by richtepa** [comment]
Hope it was the right place...

**Comment by pjhampton** [comment]
Thanks @richtepa, I have replied 💛
