### ISSUE TITLE
Front-end: Make login more classy

### ISSUE THREAD

**Issue by pjhampton** [pjhampton/Gramophone#72]
We should try make the login screen more classy. Purple was the old brand. I think we should look to a more grey / black login screen by default now if possible that is visually appealing

![screen shot 2017-10-01 at 5 42 52 pm](https://user-images.githubusercontent.com/8960296/31056831-246fbc2c-a6d0-11e7-8b76-a575e0668d33.png)

**Comment by fiott248** [comment]
You want to change the colors ?

**Comment by gdsrosa** [comment]
Hey, do you wanna change the purple background to black? Or some mixing between black and grey?

**Comment by geekfred** [comment]
If you don't mind my asking. I am new on this Hacktoberfest stuff. This is labeled as Hacktoberfest, what's the idea, to redesign the login and show you some ideas? or what? thanks.

**Comment by pjhampton** [comment]
@fiott248  @gdsrosa @geekfred Yes, but it should look good. It helps if you have a design eye. It shouldn't just be a color change to #000 and then job done.

**Comment by geekfred** [comment]
Oh! Maybe I have a designers eye! Let’s see! :D

**Comment by pjhampton** [comment]
Ok, @geekfred. It's all yours 👍

**Comment by geekfred** [comment]
![web 1920 1 2x](https://user-images.githubusercontent.com/7672885/31058647-9f478542-a6bc-11e7-93be-dfd01329df7c.png)

So classy?

**Comment by pjhampton** [comment]
Wow, yeah. This looks amazing @geekfred! Send a PR 💛

**Comment by Justicimo** [comment]
I threw this quickly together as well. If you would be interested in me submitting this as a PR let me know.

![gramophoneloginsample](https://user-images.githubusercontent.com/17466875/31058766-b1e9ff66-a6be-11e7-8221-8fc3e6847013.png)

**Comment by pjhampton** [comment]
Thanks @Justicimo 

I'm afraid this PR was claimed. Please keep an eye on this repo though, I will come up with more issues for you to work on 💛

**Comment by pjhampton** [comment]
Fixed in https://github.com/pjhampton/Gramophone/pull/75
