### ISSUE TITLE
Backend: Add new footer menu

### ISSUE THREAD

**Issue by pjhampton** [pjhampton/Gramophone#73]
**Requirements:** Add a new footer menu for the default theme. It might be a good idea to start off the theme with the unit test data: https://codex.wordpress.org/Theme_Unit_Test

![screen shot 2017-10-01 at 5 44 53 pm](https://user-images.githubusercontent.com/8960296/31056847-60816288-a6d0-11e7-8d2c-9c35bf7f4383.png)

**Comment by RickBakkr** [comment]
I will do it if I find the time to in the upcoming week :-)

**Comment by pjhampton** [comment]
Thanks @RickBakkr, it's all yours!

**Comment by RickBakkr** [comment]
Funny how this project is almost left for dead after the previous Hacktoberfest and now is alive again :')

**Comment by pjhampton** [comment]
It's stable software @RickBakkr. Only small tweaks and refinements are needed from here on out.

**Comment by RickBakkr** [comment]
Despite I shouldn't do this, so the last message before this turns completely off-topic: how about someone putting up a hosted demo? I'd be happy to push it onto one of my servers :-)

**Comment by pjhampton** [comment]
Yeah, that could be a good idea actually. I should probably order a domain.

**Comment by pjhampton** [comment]
Hey @RickBakkr! Just checking in 😄  any update?

**Comment by RickBakkr** [comment]
Hi @pjhampton 
Not yet, didn't have the time I wish I had. Will try to do this somewhere this week! :-)

**Comment by pjhampton** [comment]
Awesome! Thanks for the update @RickBakkr

**Comment by geekfred** [comment]
pj! How is this going? it seems to be taken but if Rick is too busy I could also give you a hand so we make the menu to look like the login! let me know! Best for you both.

**Comment by RickBakkr** [comment]
@geekfred Give me a little more time, hope to have finished before the end of this week (Sunday) :-)

**Comment by geekfred** [comment]
@RickBakkr nice! just let me know if you guys need help! Everything's looking good so far! Congrats!

**Comment by RickBakkr** [comment]
Just had the time to get started, what did you really have in mind like design @pjhampton ? A centered bar of links, or... ?

**Comment by pjhampton** [comment]
Hey @RickBakkr, yep - exactly. Nothing fancy! Just a simple line of links

**Comment by RickBakkr** [comment]
What'd you guys think about this?
https://imgur.com/a/taa9d

If you agree, I will push it and turn it into a PR :-)

**Comment by pjhampton** [comment]
Looks good @RickBakkr!

**Comment by RickBakkr** [comment]
Done.

**Comment by pjhampton** [comment]
Nice, thanks @RickBakkr. I will review tomorrow 👍
