### ISSUE TITLE
Link admin logo to home page

### ISSUE THREAD

**Issue by pjhampton** [pjhampton/Gramophone#77]
Currently the logo on the homepage redirects to the wordpress.org site, it should redirect to the users homepage.

![screen shot 2017-10-05 at 8 54 01 pm](https://user-images.githubusercontent.com/8960296/31249666-1c7b2d9c-aa10-11e7-8f7f-89a3f5982eba.png)

To claim this issue, comment below.

**Comment by LyNac** [comment]
I can fix it!

**Comment by pjhampton** [comment]
Hey @LyNac. Thanks!
It's all yours 🤘

**Comment by LyNac** [comment]
Cool!

**Comment by LyNac** [comment]
![lynac_logo_redirect](https://user-images.githubusercontent.com/30939927/31299653-8a4f4594-aabd-11e7-8296-8fb5a5b7d80b.jpg)

How's this?

**Comment by pjhampton** [comment]
Hey @LyNac 
Conceptually this looks great! But I need to see the code. Can you please submit a PR and I will check it out on my end?

**Comment by LyNac** [comment]
Thanks! I just submitted the PR!
