### ISSUE TITLE
Style comments

### ISSUE THREAD

**Issue by pjhampton** [pjhampton/Gramophone#80]
If you install the theme and install the [theme test data](https://codex.wordpress.org/Theme_Unit_Test) you can see that the comments don't look so good. This could be a good opportunity to style that section. As this is a starter theme, **the result should be very simple and bootstrap 4 based!**
Please comment below if you would be interested in taking forward this issue! 

![screen shot 2017-10-07 at 9 43 33 am](https://user-images.githubusercontent.com/8960296/31306283-974e8ad4-ab44-11e7-8239-e6af190c6548.png)

**Comment by vkolova** [comment]
I'd like to help!

**Comment by pjhampton** [comment]
@vkolova that would be awesome :) thank you!

**Comment by RickBakkr** [comment]
Sorry for disturbing.. Just to offer my volunteering: if things don't work out for @vkolova I'd be happy to do this one :-)

**Comment by pjhampton** [comment]
Hey @vkolova 

Any update here? If you are no longer interested can you please give @RickBakkr the go ahead 👍

**Comment by vkolova** [comment]
@RickBakkr, go ahead!

**Comment by RickBakkr** [comment]
Thanks! How about this:
![Screenie](https://i.imgur.com/iGcgiTt.png)

**Comment by pjhampton** [comment]
This looks really awesome @RickBakkr. Let me check out your code locally and I will give some feedback 👍
