### ISSUE TITLE
Remember post display choice

### ISSUE THREAD

**Issue by pjhampton** [pjhampton/Gramophone#85]
Currently, there are two ways to view the posts on home.php - grid (default) and list. However, when a user selects another page via the pagination, the selection is lost. We need some way to set a cookie to remember the users choice -`jquery.setCookie`

**Screenshot 1** - grid view
![1](https://user-images.githubusercontent.com/8960296/31514956-6a4c9c74-af8b-11e7-9b10-a2e267848401.png)

**Screenshot 2** - list view
![2](https://user-images.githubusercontent.com/8960296/31514957-6a6c94e8-af8b-11e7-8abf-e72beb1f6935.png)

**Screenshot 3** - pagination
![3](https://user-images.githubusercontent.com/8960296/31514958-6a8be352-af8b-11e7-9803-00808bffce7e.png)

**Comment by nova4005** [comment]
I would like to work on this.
