### ISSUE TITLE
Add featured thumbnail in grid view

### ISSUE THREAD

**Issue by pjhampton** [pjhampton/Gramophone#88]
Currently, home.php has a hardcoded placeholder image (See image below): https://github.com/pjhampton/Gramophone/blob/master/home.php#L54

It would be good to put the featured image there or default to that placeholder image until I can find the time to design one. 

![screen shot 2017-10-13 at 8 09 26 pm](https://user-images.githubusercontent.com/8960296/31562552-cd01ce84-b053-11e7-9f70-04f3dea9f2bb.png)

**Comment by logichub** [comment]
May I do it?

**Comment by pjhampton** [comment]
Of course, @logichub! Thanks 😄 
Reach out if you have any questions or need any help 👍

**Comment by logichub** [comment]
Thanks!

**Comment by logichub** [comment]
2 questions:
1. If post has featured image, we will use it. What if it doesn't have any?
2. What if posts have featured image in different sizes like in the screenshot:

![image](https://user-images.githubusercontent.com/6245858/31567522-57c291d6-b089-11e7-92b7-990adc80dca0.png)

**Comment by pjhampton** [comment]
@logichub sure!

> 1. If post has featured image, we will use it. What if it doesn't have any?

We can default to the existing image for the time being. 

> What if posts have featured image in different sizes like in the screenshot

That's ok for now. I can imagine I will implement a specific thumbnail size for this put we can probably just leave it atm.

**Comment by RickBakkr** [comment]
The pull request (which is in his own repo though) LGTM. Good job! I doubt whether it'd be a good idea to push IDE-specific gitignore entries to the repo as well...

**Comment by pjhampton** [comment]
Nice @logichub! Can you please create a pull request on this repo so @RickBakkr and I can review / test? :-)

**Comment by logichub** [comment]
> The pull request (which is in his own repo though) LGTM. Good job! 

> Nice @logichub! 

Thanks for your appreciation.

> I doubt whether it'd be a good idea to push IDE-specific gitignore entries to the repo as well...

@RickBakkr I added those files to ignore list as those were not part of the theme. Not sure whether it is good or not.

> Can you please create a pull request on this repo so @RickBakkr and I can review / test? 

@pjhampton I am new to git and still learning things. I created a new pull request to this repo. Can you check if it is good or again I made some mistake?
