### ISSUE TITLE
Style Gallery

### ISSUE THREAD

**Issue by pjhampton** [pjhampton/Gramophone#92]
The **gallery post format** needs to be styled with basic bootstrap styles. You can get the dummy data from: https://codex.wordpress.org/Theme_Unit_Test

![screen shot 2017-10-14 at 10 28 53 pm](https://user-images.githubusercontent.com/8960296/31579953-fc72fdaa-b139-11e7-9890-c51438512bb7.png)

If you are interested, please comment on the issue below 😄 👇

**Comment by Markandeya** [comment]
@pjhampton  I would like to help, what should I do?

**Comment by pjhampton** [comment]
Awesome, @Markandeya! It would be amazing for you to get involved. This issue could get a little tricky so if you change your mind that is fine too 😄 

You will want to add a basic bootstrap style to the images in the gallery post format.

**Comment by Markandeya** [comment]
Thank you but I shall require your help if possible. I am new to Wordpress
though I have experience working with Laravel framework.
I have setup the project as per your GIthub page instructions.

**Comment by pjhampton** [comment]
What help do you need specifically @Markandeya?

**Comment by Markandeya** [comment]
I have never worked with Wordpress or templates. Resource to Wordpress theme and the files I need to work with would be a good start ;)
I am a noob at this.

**Comment by RickBakkr** [comment]
How are things working for you @Markandeya ?
