### ISSUE TITLE
Remove line from CONTRIBUTING.md

### ISSUE THREAD

**Issue by pjhampton** [pjhampton/Gramophone#93]
The line `Import the WooCommerce dummy data` in [CONTRIBUTING.md](https://github.com/pjhampton/Gramophone/blob/master/.github/CONTRIBUTING.md) needs removed as we don't support that anymore.

### Important!

  - This issue is reserved for someone who hasn't contributing to this project before
  - Please comment below 👇  if you want this issue. First person to claim, it's all theirs 😄

**Comment by shawnlknight** [comment]
I'd like to take this issue!

**Comment by pjhampton** [comment]
Go for it @shawnlknight 👍  Let me know if you need any help
