### ISSUE TITLE
Fix home.php title

### ISSUE THREAD

**Issue by pjhampton** [pjhampton/Gramophone#94]
Currently, the [the home.php](https://github.com/pjhampton/Gramophone/blob/master/home.php#L26) is showing the title of the first post. This is wrong, it should read:

**Page \<number\>**

based on the pagination number. **This might be a difficult issue.** Please read the projects CONTRIBUTING.md before claiming this issue.

![screen shot 2017-10-15 at 9 39 45 pm](https://user-images.githubusercontent.com/8960296/31588995-e1b7dc20-b1f1-11e7-9dc8-66461f238652.png)

**Comment by alisentas** [comment]
Ok, I would like to help. Can I take this? Made a [little research](https://stackoverflow.com/questions/1031442/finding-current-page-number-in-wordpress) about getting page number as well.

**Comment by emalgamatedsoy** [comment]
inside of the ./config/pagination.php

is there a way to return the correct page number through a loop that will detect whether the page as an argument is a certain page, then include pagination in namespace clause of ./home.php?

**Comment by katiequin335** [comment]
https://github.com/pjhampton/Gramophone/pull/96 I came up with a fix using `get_query_var('paged')` to get the page number.
