### ISSUE TITLE
Remove subfooter when menu not there

### ISSUE THREAD

**Issue by pjhampton** [pjhampton/Gramophone#98]
Currently, the sub footer shows even when there is no menu there. This should be conditioned to show only if a menu is registered there. Please comment below 👇  if you want to work on this. First claimer gets it.

![screen shot 2017-10-17 at 8 24 30 pm](https://user-images.githubusercontent.com/8960296/31685119-d4b796da-b379-11e7-9988-d7c847904353.png)

**Comment by Braunson** [comment]
On it.
